[package]
name = "egui_track_example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "egui_track_example"
path = "src/main.rs"

[dependencies]
eframe = "0.30"
egui = "0.30"
egui_track = { path = "../egui_track" }
env_logger = "0.10"
log = "0.4"
rfd = "0.14"
